services:
  p2mpptorch:
    # you can change this to whatever you want.
    container_name: p2mpptorch
    build:
      context: ./
      dockerfile: ./Dockerfile
      shm_size: '100gb'
    shm_size: '100gb'
    volumes:
      - "./:/P2MPP"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]